#nullable enable
using Newtonsoft.Json;

namespace Mochineko.ChatGPT_API
{
    /// <summary>
    /// A message between user, assistant and system.
    /// </summary>
    [JsonObject]
    public sealed class Message
    {
        /// <summary>
        /// [Required]
        /// The role of the messages author.
        /// </summary>
        [JsonProperty("role"), JsonRequired]
        public string RoleString
        {
            get => this.Role.ToText();
            set => this.Role = value.ToRole();
        }
        /// <summary>
        /// [Required]
        /// The role of the messages author.
        /// </summary>
        [JsonIgnore]
        public Role Role { get; private set; }
        
        /// <summary>
        /// [Optional]
        /// The contents of the message.
        /// "content" is required for all messages except assistant messages with function calls.
        /// </summary>
        [JsonProperty("content")]
        public string? Content { get; internal set; }
        
        /// <summary>
        /// [Optional]
        /// The name of the author of this message.
        /// "name" is required if role is "function", and it should be the name of the function whose response is in the "content".
        /// May contain a-z, A-Z, 0-9, and underscores, with a maximum length of 64 characters.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; private set; }
        
        /// <summary>
        /// [Optional]
        /// The name and arguments of a function that should be called, as generated by the model.
        /// </summary>
        [JsonProperty("function_call")]
        public FunctionCall? FunctionCall { get; private set; }
        
        internal Message()
        {
            this.Role = Role.Assistant;
            this.Content = string.Empty;
        }
        
        public Message(
            Role role,
            string? content = null,
            string? name = null,
            FunctionCall? functionCall = null)
        {
            this.Role = role;
            this.Content = content;
            this.Name = name;
            this.FunctionCall = functionCall;
        }
    }
}