#nullable enable
using Newtonsoft.Json;

namespace Mochineko.ChatGPT_API
{
    [JsonObject]
    public sealed class ToolFunction
    {
        /// <summary>
        /// [Required]
        /// The name of the function to call.
        /// </summary>
        [JsonProperty("name"), JsonRequired]
        public string Name { get; private set; } = string.Empty;

        /// <summary>
        /// [Required]
        /// The arguments to call the function with, as generated by the model in JSON format.
        /// Note that the model does not always generate valid JSON, and may hallucinate parameters not defined by your function schema.
        /// Validate the arguments in your code before calling your function.
        /// </summary>
        [JsonProperty("arguments"), JsonRequired]
        public string Arguments { get; private set; } = string.Empty;
    }
}